const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const BASE=process.env.TEUM_DATA_DIR||path.join(__dirname,'data');
const UP=path.join(BASE,'uploads');fs.mkdirSync(UP,{recursive:true});
const db=new DatabaseSync(path.join(BASE,'teum.sqlite'));
db.exec(`PRAGMA foreign_keys=ON;PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,name TEXT NOT NULL,city TEXT DEFAULT '',bio TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires INTEGER NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,price INTEGER,city TEXT DEFAULT '',tags TEXT DEFAULT '',image TEXT DEFAULT '',status TEXT DEFAULT 'OPEN',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER NOT NULL,sender_id INTEGER NOT NULL,receiver_id INTEGER NOT NULL,body TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(receiver_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,reviewer_id INTEGER NOT NULL,reviewee_id INTEGER NOT NULL,post_id INTEGER NOT NULL,rating INTEGER NOT NULL,body TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(reviewer_id,post_id),FOREIGN KEY(reviewer_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(reviewee_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,reporter_id INTEGER NOT NULL,post_id INTEGER,reason TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(reporter_id) REFERENCES users(id) ON DELETE CASCADE);`);
const clients=new Map();
const types=new Set(['팝니다','구합니다','레슨','서비스','수제품']);
function send(res,s,d,h={}){res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h});res.end(JSON.stringify(d));}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}));}
function me(req){const t=cookies(req).teum;return t?db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?').get(t,Date.now()):null;}
function startSession(res,id){const t=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(t,id,Date.now()+2592000000);res.setHeader('Set-Cookie',`teum=${t}; HttpOnly; Path=/; SameSite=Lax; Max-Age=2592000${process.env.NODE_ENV==='production'?'; Secure':''}`)}
function endSession(req,res){const t=cookies(req).teum;if(t)db.prepare('DELETE FROM sessions WHERE token=?').run(t);res.setHeader('Set-Cookie','teum=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0')}
function pw(p){const s=crypto.randomBytes(16).toString('hex');return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function okpw(p,e){const [s,h]=String(e).split(':');const x=crypto.scryptSync(p,s,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(x,'hex'),Buffer.from(h,'hex'))}
async function body(req){let s='',n=0;for await(const c of req){n+=c.length;if(n>9000000)throw Error('payload');s+=c}return s?JSON.parse(s):{}}
function score(a,b){const A=(a.title+' '+a.description+' '+a.tags).toLowerCase(),B=(b.title+' '+b.description+' '+b.tags).toLowerCase();let v=0;for(const t of new Set(A.split(/[^a-z0-9가-힣]+/i).filter(x=>x.length>1)))if(B.includes(t))v+=Math.min(4,t.length/3);if(a.city&&b.city&&(a.city.includes(b.city)||b.city.includes(a.city)))v+=3;if(a.price&&b.price&&Number(b.price)<=Number(a.price))v+=3;return v}
function matches(w){return db.prepare(`SELECT p.*,u.name FROM posts p JOIN users u ON u.id=p.user_id WHERE p.status='OPEN' AND p.type IN ('팝니다','수제품','레슨','서비스') AND p.id<>? ORDER BY p.id DESC`).all(w.id).map(p=>({...p,score:score(w,p)})).filter(p=>p.score>=4).sort((a,b)=>b.score-a.score).slice(0,8)}
function notify(uid,data){for(const r of clients.get(uid)||[])try{r.write('data: '+JSON.stringify(data)+'\n\n')}catch{}}
async function api(req,res,u){
 const m=req.method;
 if(m==='GET'&&u==='/api/health')return send(res,200,{ok:true,time:new Date().toISOString()});
 if(m==='GET'&&u==='/api/me'){const x=me(req);return send(res,200,{user:x?{id:x.id,username:x.username,name:x.name,city:x.city,bio:x.bio}:null})}
 if(m==='POST'&&u==='/api/register'){const b=await body(req);if(!b.username||!b.password||String(b.password).length<4)return send(res,400,{error:'닉네임과 4자 이상 비밀번호가 필요합니다.'});try{const x=db.prepare('INSERT INTO users(username,password_hash,name,city,bio) VALUES(?,?,?,?,?)').run(String(b.username).trim(),pw(String(b.password)),String(b.name||b.username).trim(),String(b.city||''),String(b.bio||''));startSession(res,Number(x.lastInsertRowid));return send(res,201,{ok:true})}catch{return send(res,409,{error:'이미 사용 중인 닉네임입니다.'})}}
 if(m==='POST'&&u==='/api/login'){const b=await body(req),x=db.prepare('SELECT * FROM users WHERE username=?').get(String(b.username||'').trim());if(!x||!okpw(String(b.password||''),x.password_hash))return send(res,401,{error:'닉네임 또는 비밀번호가 맞지 않습니다.'});startSession(res,x.id);return send(res,200,{user:{id:x.id,username:x.username,name:x.name,city:x.city,bio:x.bio}})}
 if(m==='POST'&&u==='/api/logout'){endSession(req,res);return send(res,200,{ok:true})}
 if(m==='GET'&&u==='/api/posts'){const q=new URL(req.url,'http://x').searchParams,t=q.get('type')||'',s=(q.get('q')||'').toLowerCase();let a=db.prepare(`SELECT p.*,u.name FROM posts p JOIN users u ON u.id=p.user_id WHERE (?='' OR p.type=?) AND p.status<>'HIDDEN' ORDER BY p.id DESC`).all(t,t);if(s)a=a.filter(x=>(x.title+' '+x.description+' '+x.tags+' '+x.city).toLowerCase().includes(s));return send(res,200,{posts:a})}
 if(m==='GET'&&/^\/api\/posts\/\d+$/.test(u)){const id=+u.split('/').pop(),p=db.prepare(`SELECT p.*,u.name FROM posts p JOIN users u ON u.id=p.user_id WHERE p.id=?`).get(id);if(!p)return send(res,404,{error:'게시글이 없습니다.'});return send(res,200,{post:p,matches:p.type==='구합니다'?matches(p):[],reviews:db.prepare(`SELECT r.*,u.name FROM reviews r JOIN users u ON u.id=r.reviewer_id WHERE r.post_id=? ORDER BY r.id DESC`).all(id)})}
 if(m==='POST'&&u==='/api/posts'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'});const b=await body(req);if(!types.has(b.type)||!b.title||!b.description)return send(res,400,{error:'종류·제목·설명을 입력하세요.'});const r=db.prepare('INSERT INTO posts(user_id,type,title,description,price,city,tags,image) VALUES(?,?,?,?,?,?,?,?)').run(x.id,b.type,String(b.title).trim(),String(b.description).trim(),b.price===''?null:(b.price==null?null:+b.price),String(b.city||''),String(b.tags||''),String(b.image||''));const p=db.prepare(`SELECT p.*,u.name FROM posts p JOIN users u ON u.id=p.user_id WHERE p.id=?`).get(Number(r.lastInsertRowid));if(p.type==='구합니다')for(const mm of matches(p))notify(x.id,{type:'match',want:p,match:mm});return send(res,201,{post:p})}
 if(m==='POST'&&u==='/api/upload'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'});const b=await body(req),ext={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp'}[b.mime];if(!ext||!b.data)return send(res,400,{error:'JPG/PNG/WEBP 이미지만 업로드할 수 있습니다.'});const raw=String(b.data).replace(/^data:[^;]+;base64,/,'');if(raw.length>7000000)return send(res,400,{error:'사진이 너무 큽니다.'});const id=crypto.randomBytes(12).toString('hex')+ext;fs.writeFileSync(path.join(UP,id),Buffer.from(raw,'base64'));return send(res,201,{url:'/uploads/'+id})}
 if(m==='POST'&&u==='/api/message'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'});const b=await body(req),p=db.prepare('SELECT * FROM posts WHERE id=?').get(+b.post_id);if(!p)return send(res,404,{error:'게시글이 없습니다.'});if(p.user_id===x.id)return send(res,400,{error:'내 게시글에는 메시지를 보낼 수 없습니다.'});const text=String(b.body||'').trim();if(!text||text.length>2000)return send(res,400,{error:'메시지를 확인하세요.'});const r=db.prepare('INSERT INTO messages(post_id,sender_id,receiver_id,body) VALUES(?,?,?,?)').run(p.id,x.id,p.user_id,text);const msg=db.prepare(`SELECT m.*,a.name sender_name,b.name receiver_name FROM messages m JOIN users a ON a.id=m.sender_id JOIN users b ON b.id=m.receiver_id WHERE m.id=?`).get(Number(r.lastInsertRowid));notify(p.user_id,{type:'message',message:msg});return send(res,201,{message:msg})}
 if(m==='GET'&&u==='/api/messages'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'});return send(res,200,{messages:db.prepare(`SELECT m.*,a.name sender_name,b.name receiver_name,p.title FROM messages m JOIN users a ON a.id=m.sender_id JOIN users b ON b.id=m.receiver_id JOIN posts p ON p.id=m.post_id WHERE m.sender_id=? OR m.receiver_id=? ORDER BY m.id ASC`).all(x.id,x.id)})}
 if(m==='GET'&&u==='/api/events'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'},{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache','Connection':'keep-alive'});res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache','Connection':'keep-alive'});res.write('data: '+JSON.stringify({type:'connected'})+'\n\n');if(!clients.has(x.id))clients.set(x.id,new Set);clients.get(x.id).add(res);req.on('close',()=>clients.get(x.id)?.delete(res));return}
 if(m==='POST'&&u==='/api/status'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'});const b=await body(req),p=db.prepare('SELECT * FROM posts WHERE id=?').get(+b.post_id);if(!p||p.user_id!==x.id)return send(res,403,{error:'권한이 없습니다.'});if(!['OPEN','RESERVED','DONE','HIDDEN'].includes(b.status))return send(res,400,{error:'상태가 잘못되었습니다.'});db.prepare('UPDATE posts SET status=? WHERE id=?').run(b.status,p.id);return send(res,200,{ok:true})}
 if(m==='POST'&&u==='/api/review'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'});const b=await body(req),p=db.prepare('SELECT * FROM posts WHERE id=?').get(+b.post_id);if(!p||p.user_id===x.id)return send(res,400,{error:'후기를 남길 수 없습니다.'});const r=Math.max(1,Math.min(5,+b.rating));try{db.prepare('INSERT INTO reviews(reviewer_id,reviewee_id,post_id,rating,body) VALUES(?,?,?,?,?)').run(x.id,p.user_id,p.id,r,String(b.body||''));return send(res,201,{ok:true})}catch{return send(res,409,{error:'이미 후기를 남겼습니다.'})}}
 if(m==='POST'&&u==='/api/report'){const x=me(req);if(!x)return send(res,401,{error:'로그인이 필요합니다.'});const b=await body(req);if(!b.reason)return send(res,400,{error:'신고 사유를 입력하세요.'});db.prepare('INSERT INTO reports(reporter_id,post_id,reason) VALUES(?,?,?)').run(x.id,b.post_id?+b.post_id:null,String(b.reason).slice(0,1000));return send(res,201,{ok:true})}
 return send(res,404,{error:'Not Found'})
}
const html=path.join(__dirname,'public','index.html');const mime={'html':'text/html; charset=utf-8','js':'text/javascript; charset=utf-8','css':'text/css; charset=utf-8','png':'image/png','jpg':'image/jpeg','jpeg':'image/jpeg','webp':'image/webp'};
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname.startsWith('/api/'))return await api(req,res,u.pathname);if(u.pathname.startsWith('/uploads/')){const f=path.join(UP,path.basename(u.pathname));if(fs.existsSync(f))return fs.createReadStream(f).pipe(res);return send(res,404,{error:'Not Found'})}const f=u.pathname==='/'?html:path.join(__dirname,'public',path.normalize(u.pathname).replace(/^\/+/,''));if(!f.startsWith(path.join(__dirname,'public'))||!fs.existsSync(f))return send(res,404,{error:'Not Found'});res.writeHead(200,{'Content-Type':mime[path.extname(f).slice(1)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}catch(e){console.error(e);if(!res.headersSent)send(res,500,{error:'서버 오류'})}});
const PORT=process.env.PORT||3000;server.listen(PORT,'0.0.0.0',()=>console.log('TEUM '+PORT));
